// <auto-generated />
namespace DbCreator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class index_creation_on_system_date_endpoint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(index_creation_on_system_date_endpoint));
        
        string IMigrationMetadata.Id
        {
            get { return "201707191336553_index_creation_on_system_date_endpoint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
