// <auto-generated />
namespace DbCreator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_column_and_index_creation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_column_and_index_creation));
        
        string IMigrationMetadata.Id
        {
            get { return "201707191333224_added_column_and_index_creation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
